Рефакторинг после РК1
go-park-mail-ru/2024_1_Cyberkotletki pull request #5
Opened 2024-03-19 16:25 UTC by blackHATred

2024-03-21 10:58 UTC, ygimm requested changes
Очень хороший рефакторинг, очень хорошо написаны тесты (структура, нейминги и тд), реально кайфанул, пока читал код, хоть и есть парочка недостатков

есть два замечания, которые несложно поправить: 
- тесты не распараллелены
- нет линтера (и вытекающие отсюда стилистические недостатки)

линтер может увидеть больше стилистических ошибок, чем я (я по факту одну нашел), поэтому подключаем обязательно в ci (чтобы джоба падала при упавшем линтере) и кофнигурируем специальным файликом, чтобы он ругался в том числе и на отсутсвие комментов и на несортированные импорты и так далее

2024-03-21 10:58 UTC, ygimm commented on .gitignore
> +config.yaml
предлагаю запушить конфиг (хотя бы для примера config.example.yaml)

2024-03-21 10:58 UTC, ygimm commented on Dockerfile
> +FROM golang:1.22.1-alpine3.19 AS build
респект за мультистейдж билд 

 хотелось бы увидеть сколько собирается контейнер и сколько он весит (пока у вас нет автодеплоя, не могу логи в ci посмотреть)

2024-03-21 10:58 UTC, ygimm commented on internal/app/app.go
> +	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
предлагаю добавить еще panic recovery и логирующую middleware. готовые брать нельзя)

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/auth.go
> +		// будем считать, что ErrAlreadyExists это тоже BadRequest
почему не 409 conflict?

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/auth.go
> +		// будем считать, что ErrAlreadyExists это тоже BadRequest
почему не 409 conflict?

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/auth.go
> +	key, err := h.useCase.Register(*registerData)
на дженериках можно написать безоапсные утилитки для разыменования типа FromPtr
для перевода структуры в указатель тоже можно написать всякие Ptr, PtrOrNil и так далее

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/auth.go
> +	key, err := h.useCase.Register(*registerData)
а почему бы не поменять интерфейс usecae просто?..

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/auth_test.go
> +				require.Equal(t, tc.ExpectedErr(c), err)
есть ErrorIs для сравнения ошибок (и можно будет более гибко с ними работать)

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/auth_test.go
> +func TestAuthEndpoints_IsAuth(t *testing.T) {
а давйте распараллелим тесты?
не зря же мы табличное тестирвоание и моки придумали.
придется создавать моки и тестируемые сущности внтури каждого теста, но это все равно будет быстрее благодаря параллельным запускам тестов

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/content.go
> +	}
`
if entity.Contains(err, entity.ErrNotFound) {
			return echoutil.NewError(c, http.StatusNotFound, err)
		} 
		return echoutil.NewError(c, http.StatusInternalServerError, err)
		
`
почему не так? давайте уменьшать вложенность, код будет читаемее и проще
на все подобные места я не буду обращать внимание, правьте по мере нахождения.

к слову, линтер должен такое обнаруживать

2024-03-21 10:58 UTC, ygimm commented on .github/workflows/tests.yml
> +        echo $coverage
а линтера у нас и нет))

давайте добавим линтер golangcilint. это стандартный линтер, много где используется. также давайте настроим yaml-файл для его конфигурации

2024-03-21 10:58 UTC, ygimm commented on internal/delivery/http/content.go
> +	}
оставил коммент про линтер, обратите внимание, пожалуйста

2024-03-21 10:58 UTC, ygimm commented on internal/repository/user.go
> +type User interface {
мне нравится расположение интерфейсов и имплементации, по мне так идеальный баланс в холиварной теме о том, где размещать объявления интерфейсов))

2024-03-21 10:58 UTC, ygimm commented on internal/repository/content/film.go
> +type Film interface {
интерфейс с фильмом только уехал немного. 
подскажите, имплементация будет лежать еще глубже по иерархии проекта? 
`repository/content/film/impl.go`? типа такого?

2024-03-21 11:11 UTC, blackHATred commented on .gitignore
> +config.yaml
Там есть make для генерации примера конфига)

2024-03-21 11:12 UTC, blackHATred commented on Dockerfile
> +FROM golang:1.22.1-alpine3.19 AS build
Автодеплой пока в процессе, но контейнер с рабочим сервером (чисто скомпилированная гошка без редиса и nginx, которые находятся в отдельных контейнерах) весит ~10Мб

2024-03-21 23:12 UTC, blackHATred commented on internal/delivery/http/auth.go
> +		// будем считать, что ErrAlreadyExists это тоже BadRequest
Как-то промахнулся с этим, забыл, что есть такой статус. Уже пофиксил

2024-03-21 23:19 UTC, blackHATred commented on internal/delivery/http/auth.go
> +	key, err := h.useCase.Register(*registerData)
Действительно, проще поменять интерфейс)
Так и сделал

2024-03-22 00:47 UTC, blackHATred commented on internal/repository/content/film.go
> +type Film interface {
Задумка изначально была в том, чтобы подробить интерфейс Content на разные куски по типу Film и Series, которые должны лежать в папке content. От этой идеи сейчас отказался

2024-03-26 08:02 UTC, ygimm approved these changes

2024-03-26 08:04 UTC, merged